- name: test hirschmann
  hosts: hirschmann
  gather_facts: false
  roles:
    - openrail.switchos.hirschmann
- name: test lantech
  connection: ansible.netcommon.network_cli
  hosts: lantech
  gather_facts: false
  tasks:
    - name: run port status on remote devices
      cli_command:
        command: port status
