- name: test
  connection: ansible.netcommon.network_cli
  hosts: foo
  gather_facts: false
  tasks:
  - name: run show port
    ignore_errors: true
    cli_command:
      command: show port
  - name: run show clock with become=yes
    become: yes
    cli_command:
      command: show clock
