- name: Add interfaces to VLANs with tagging/untagging
  become: true
  vars:
    vlan_cmds: |
      interface {{ item.interface }}
      {% for vlan in item.vlans %}
      vlan participation include {{ vlan.vlan_id }}
      {% if vlan.mode == 'tagged' %}
      vlan tagging {{ vlan.vlan_id }}
      {% else %}
      no vlan tagging {{ vlan.vlan_id }}
      {% endif %}
      {% endfor %}
      exit
  ansible.netcommon.cli_command:
    command: |
      configure
      {{ vlan_cmds }}
      exit
  loop: "{{ interfaces_vlans }}"
