---
- name: Import show vlans
  ansible.builtin.import_tasks:
    file: show_vlans.yml

- name: Import add vlans
  ansible.builtin.import_tasks:
    file: add_vlans.yml

- name: Import delete vlans
  ansible.builtin.import_tasks:
    file: delete_vlans.yml

- name: Import add interfaces to vlans
  ansible.builtin.import_tasks:
    file: add_interfaces_to_vlans.yml

- name: Import remove interfaces from vlans
  ansible.builtin.import_tasks:
    file: remove_interfaces_from_vlans.yml

# this doesnt work yet
# - name: Import show vlan members
#   ansible.builtin.import_tasks:
#     file: show_vlan_members.yml
