- name: Remove interfaces from VLANs
  become: true
  ignore_errors: true
  vars:
    vlan_cmds: |
      interface {{ item.interface }}
      {% for vlan in item.vlans %}
      vlan participation exclude {{ vlan.vlan_id }}
      {% endfor %}
      exit
  ansible.netcommon.cli_command:
    command: |
      configure
      {{ vlan_cmds }}
      exit
  loop: "{{ interfaces_vlans_to_remove }}"
