- name: Show vlan members
  become: true
  ansible.netcommon.cli_command:
    command: show vlan member current
  register: output
- debug:
    var: output
- set_fact:
    vlan_maps: "{{ output.stdout_lines | openrail.switchos.hirschmann.parse_vlan_ports_table }}"
- debug:
    var: vlan_maps.ports_to_vlans
- debug:
    var: vlan_maps.vlans_to_ports
